# Generated by Django 4.1.3 on 2024-07-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='raw_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
